"""add localization_modes on job

Revision ID: 05796006b779
Revises: d714e5ac0787
Create Date: 2026-04-20 19:22:03.374842

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "05796006b779"
down_revision: Union[str, None] = "d714e5ac0787"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Guard: initial migration (create_all) may already have added this column
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    cols = {c["name"] for c in inspector.get_columns("localization_jobs")}
    if "localization_modes" in cols:
        return
    op.add_column(
        "localization_jobs",
        sa.Column(
            "localization_modes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text(
                "'{\"language\": true, \"compliance\": true, \"element_replace\": true}'::jsonb"
            ),
        ),
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("localization_jobs", "localization_modes")
    # ### end Alembic commands ###
