"""add prompt_additions on brand and project

Revision ID: d714e5ac0787
Revises: e36934ed28e5
Create Date: 2026-04-20 19:06:08.680706

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d714e5ac0787"
down_revision: Union[str, None] = "e36934ed28e5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Guard: initial migration (create_all) may already have added these columns
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    brands_cols = {c["name"] for c in inspector.get_columns("brands")}
    if "prompt_additions" not in brands_cols:
        op.add_column(
            "brands",
            sa.Column(
                "prompt_additions",
                sa.String(length=4000),
                nullable=False,
                server_default="",
            ),
        )
    projects_cols = {c["name"] for c in inspector.get_columns("projects")}
    if "prompt_additions" not in projects_cols:
        op.add_column(
            "projects",
            sa.Column(
                "prompt_additions",
                sa.String(length=4000),
                nullable=False,
                server_default="",
            ),
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "prompt_additions")
    op.drop_column("brands", "prompt_additions")
    # ### end Alembic commands ###
