-- 0007_agent_execution_logs.sql
--
-- Stores execution logs from all agents for the Evolution Agent to analyze.
-- Each row = one agent invocation within a pipeline run.
--
-- Design choices:
--   - JSONB for metrics/input/output — schema varies per agent, JSONB is flexible
--   - text[] for tags — enables GIN index for fast filtering
--   - user_action is nullable — populated later when user interacts with output
--   - Separate indices for common Evolution Agent query patterns

create table if not exists public.agent_execution_logs (
  id                text primary key,
  run_id            text not null,
  agent_id          text not null,
  agent_version     text not null,
  brief_id          text,
  user_id           uuid references public.users(id),
  input_summary     jsonb not null default '{}'::jsonb,
  output_summary    jsonb not null default '{}'::jsonb,
  metrics           jsonb not null default '{}'::jsonb,
  user_action       text check (user_action in ('accepted', 'modified', 'rejected', 'ignored')),
  modification_diff text,
  quality_score     numeric(5,2),
  tags              text[] not null default '{}',
  created_at        timestamptz not null default now()
);

-- Evolution Agent query patterns:
-- 1. "Show me all runs for agent X in the last 7 days"
create index if not exists ael_agent_time_idx
  on public.agent_execution_logs (agent_id, created_at desc);

-- 2. "What did user Y interact with?"
create index if not exists ael_user_idx
  on public.agent_execution_logs (user_id, created_at desc)
  where user_id is not null;

-- 3. "All agents in pipeline run Z"
create index if not exists ael_run_idx
  on public.agent_execution_logs (run_id);

-- 4. "Find all logs tagged with 'error' or 'brazil'"
create index if not exists ael_tags_idx
  on public.agent_execution_logs using gin (tags);

-- 5. "Aggregate by user_action for acceptance rates"
create index if not exists ael_action_idx
  on public.agent_execution_logs (agent_id, user_action)
  where user_action is not null;

-- 6. "Quality score distribution per agent"
create index if not exists ael_quality_idx
  on public.agent_execution_logs (agent_id, quality_score)
  where quality_score is not null;


-- ─── Evolution decisions table ───────────────────────────────────────
-- Stores proposed and executed evolution decisions.

create table if not exists public.evolution_decisions (
  id                  text primary key,
  type                text not null check (type in ('enhance', 'split', 'merge', 'create', 'deprecate', 'tune')),
  urgency             text not null check (urgency in ('immediate', 'next_sprint', 'backlog', 'observation')),
  confidence          numeric(3,2) not null,
  target_agents       text[] not null,
  impact              jsonb not null default '{}'::jsonb,
  reasoning           text not null,
  action_items        jsonb not null default '[]'::jsonb,
  rollback_plan       text,
  requires_human_review boolean not null default true,
  status              text not null default 'proposed'
                        check (status in ('proposed', 'approved', 'executing', 'completed', 'rejected', 'rolled_back')),
  created_at          timestamptz not null default now(),
  resolved_at         timestamptz,
  resolved_by         text check (resolved_by in ('auto', 'human'))
);

create index if not exists ed_status_idx
  on public.evolution_decisions (status, created_at desc);

create index if not exists ed_targets_idx
  on public.evolution_decisions using gin (target_agents);


-- ─── Evolution reports table ─────────────────────────────────────────
-- Periodic analysis reports generated by Evolution Agent.

create table if not exists public.evolution_reports (
  id                  text primary key,
  period_from         timestamptz not null,
  period_to           timestamptz not null,
  agent_health        jsonb not null default '[]'::jsonb,
  system_insights     jsonb not null default '[]'::jsonb,
  decisions           text[] not null default '{}',  -- references evolution_decisions.id
  system_health_score numeric(5,2),
  executive_summary   text,
  generated_at        timestamptz not null default now()
);
